<?php

namespace Database\Seeders;

use App\Models\Team;
use Illuminate\Database\Seeder;

class AddFifaCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Agrega 210+ países FIFA a la tabla teams
     * Usa firstOrCreate para evitar duplicados
     */
    public function run(): void
    {
        $countries = [
            // CONMEBOL (10 países)
            ['name' => 'Argentina', 'fifa_code' => 'ARG', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Bolivia', 'fifa_code' => 'BOL', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Brasil', 'fifa_code' => 'BRA', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Chile', 'fifa_code' => 'CHI', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Colombia', 'fifa_code' => 'COL', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Ecuador', 'fifa_code' => 'ECU', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Paraguay', 'fifa_code' => 'PAR', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Perú', 'fifa_code' => 'PER', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Uruguay', 'fifa_code' => 'URU', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],
            ['name' => 'Venezuela', 'fifa_code' => 'VEN', 'type' => 'country', 'region' => 'South America', 'confederation' => 'CONMEBOL'],

            // UEFA (55 países)
            ['name' => 'Alemania', 'fifa_code' => 'GER', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Albania', 'fifa_code' => 'ALB', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Andorra', 'fifa_code' => 'AND', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Armenia', 'fifa_code' => 'ARM', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Austria', 'fifa_code' => 'AUT', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Azerbaiyán', 'fifa_code' => 'AZE', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Bélgica', 'fifa_code' => 'BEL', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Bielorrusia', 'fifa_code' => 'BLR', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Bosnia y Herzegovina', 'fifa_code' => 'BIH', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Bulgaria', 'fifa_code' => 'BUL', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Chipre', 'fifa_code' => 'CYP', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Croacia', 'fifa_code' => 'CRO', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Dinamarca', 'fifa_code' => 'DEN', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Escocia', 'fifa_code' => 'SCO', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Eslovaquia', 'fifa_code' => 'SVK', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Eslovenia', 'fifa_code' => 'SVN', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'España', 'fifa_code' => 'ESP', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Estonia', 'fifa_code' => 'EST', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Finlandia', 'fifa_code' => 'FIN', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Francia', 'fifa_code' => 'FRA', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Gales', 'fifa_code' => 'WAL', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Georgia', 'fifa_code' => 'GEO', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Gibraltar', 'fifa_code' => 'GIB', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Grecia', 'fifa_code' => 'GRE', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Holanda', 'fifa_code' => 'NED', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Hungría', 'fifa_code' => 'HUN', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Irlanda', 'fifa_code' => 'IRL', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Irlanda del Norte', 'fifa_code' => 'NIR', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Islandia', 'fifa_code' => 'ISL', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Italia', 'fifa_code' => 'ITA', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Kosovo', 'fifa_code' => 'KOS', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Letonia', 'fifa_code' => 'LAT', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Liechtenstein', 'fifa_code' => 'LIE', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Lituania', 'fifa_code' => 'LTU', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Luxemburgo', 'fifa_code' => 'LUX', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Macedonia del Norte', 'fifa_code' => 'MKD', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Malta', 'fifa_code' => 'MLT', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Moldavia', 'fifa_code' => 'MDA', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Mónaco', 'fifa_code' => 'MCO', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Montenegro', 'fifa_code' => 'MNE', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Noruega', 'fifa_code' => 'NOR', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Polonia', 'fifa_code' => 'POL', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Portugal', 'fifa_code' => 'POR', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Reino Unido', 'fifa_code' => 'ENG', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'República Checa', 'fifa_code' => 'CZE', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Rumania', 'fifa_code' => 'ROU', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Rusia', 'fifa_code' => 'RUS', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'San Marino', 'fifa_code' => 'SMR', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Serbia', 'fifa_code' => 'SRB', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Suecia', 'fifa_code' => 'SWE', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Suiza', 'fifa_code' => 'SUI', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Turquía', 'fifa_code' => 'TUR', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],
            ['name' => 'Ucrania', 'fifa_code' => 'UKR', 'type' => 'country', 'region' => 'Europe', 'confederation' => 'UEFA'],

            // CONCACAF (35 países)
            ['name' => 'Antigua y Barbuda', 'fifa_code' => 'ATG', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Bahamas', 'fifa_code' => 'BAH', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Barbados', 'fifa_code' => 'BRB', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Belice', 'fifa_code' => 'BLZ', 'type' => 'country', 'region' => 'Central America', 'confederation' => 'CONCACAF'],
            ['name' => 'Canadá', 'fifa_code' => 'CAN', 'type' => 'country', 'region' => 'North America', 'confederation' => 'CONCACAF'],
            ['name' => 'Costa Rica', 'fifa_code' => 'CRC', 'type' => 'country', 'region' => 'Central America', 'confederation' => 'CONCACAF'],
            ['name' => 'Cuba', 'fifa_code' => 'CUB', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Curazao', 'fifa_code' => 'CUW', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Dominica', 'fifa_code' => 'DMA', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'El Salvador', 'fifa_code' => 'SLV', 'type' => 'country', 'region' => 'Central America', 'confederation' => 'CONCACAF'],
            ['name' => 'Estados Unidos', 'fifa_code' => 'USA', 'type' => 'country', 'region' => 'North America', 'confederation' => 'CONCACAF'],
            ['name' => 'Granada', 'fifa_code' => 'GRD', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Guadalupe', 'fifa_code' => 'GLP', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Guatemala', 'fifa_code' => 'GUA', 'type' => 'country', 'region' => 'Central America', 'confederation' => 'CONCACAF'],
            ['name' => 'Guyana Francesa', 'fifa_code' => 'GUF', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Haití', 'fifa_code' => 'HAI', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Honduras', 'fifa_code' => 'HND', 'type' => 'country', 'region' => 'Central America', 'confederation' => 'CONCACAF'],
            ['name' => 'Islas Caimán', 'fifa_code' => 'CAY', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Islas Turcas y Caicos', 'fifa_code' => 'TCA', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Islas Vírgenes Británicas', 'fifa_code' => 'VGB', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Islas Vírgenes de EE.UU.', 'fifa_code' => 'VIR', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Jamaica', 'fifa_code' => 'JAM', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Martinica', 'fifa_code' => 'MTQ', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'México', 'fifa_code' => 'MEX', 'type' => 'country', 'region' => 'North America', 'confederation' => 'CONCACAF'],
            ['name' => 'Montserrat', 'fifa_code' => 'MSR', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Nicaragua', 'fifa_code' => 'NCA', 'type' => 'country', 'region' => 'Central America', 'confederation' => 'CONCACAF'],
            ['name' => 'Panamá', 'fifa_code' => 'PAN', 'type' => 'country', 'region' => 'Central America', 'confederation' => 'CONCACAF'],
            ['name' => 'Puerto Rico', 'fifa_code' => 'PUR', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'República Dominicana', 'fifa_code' => 'DOM', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'San Cristóbal y Nieves', 'fifa_code' => 'KNA', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'San Vicente y las Granadinas', 'fifa_code' => 'VCT', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Santa Lucía', 'fifa_code' => 'LCA', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],
            ['name' => 'Trinidad y Tobago', 'fifa_code' => 'TRI', 'type' => 'country', 'region' => 'Caribbean', 'confederation' => 'CONCACAF'],

            // AFC (47 países)
            ['name' => 'Arabia Saudí', 'fifa_code' => 'KSA', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Afganistán', 'fifa_code' => 'AFG', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Australia', 'fifa_code' => 'AUS', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'AFC'],
            ['name' => 'Bahréin', 'fifa_code' => 'BHR', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Bangladesh', 'fifa_code' => 'BHN', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Bután', 'fifa_code' => 'BHU', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Brunéi', 'fifa_code' => 'BRU', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Camboya', 'fifa_code' => 'CAM', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'China', 'fifa_code' => 'CHN', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Corea del Norte', 'fifa_code' => 'PRK', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Corea del Sur', 'fifa_code' => 'KOR', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Emiratos Árabes Unidos', 'fifa_code' => 'UAE', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Filipinas', 'fifa_code' => 'PHI', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Hong Kong', 'fifa_code' => 'HKG', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'India', 'fifa_code' => 'IND', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Indonesia', 'fifa_code' => 'IDN', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Irak', 'fifa_code' => 'IRQ', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Irán', 'fifa_code' => 'IRN', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Israel', 'fifa_code' => 'ISR', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Japón', 'fifa_code' => 'JPN', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Jordania', 'fifa_code' => 'JOR', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Kazajistán', 'fifa_code' => 'KAZ', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Kirguistán', 'fifa_code' => 'KGZ', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Kuwait', 'fifa_code' => 'KUW', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Laos', 'fifa_code' => 'LAO', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Líbano', 'fifa_code' => 'LIB', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Macao', 'fifa_code' => 'MAC', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Malasia', 'fifa_code' => 'MAS', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Maldivas', 'fifa_code' => 'MDV', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Mongolia', 'fifa_code' => 'MNG', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Myanmar', 'fifa_code' => 'MYA', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Nepal', 'fifa_code' => 'NEP', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Omán', 'fifa_code' => 'OMA', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Palestina', 'fifa_code' => 'PLE', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Pakistán', 'fifa_code' => 'PAK', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Qatar', 'fifa_code' => 'QAT', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Singapur', 'fifa_code' => 'SGP', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Siria', 'fifa_code' => 'SYR', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Sri Lanka', 'fifa_code' => 'SRI', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Tailandia', 'fifa_code' => 'THA', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Taiwán', 'fifa_code' => 'TWN', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Tayikistán', 'fifa_code' => 'TJK', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Timor Oriental', 'fifa_code' => 'TLS', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Turkmenistán', 'fifa_code' => 'TKM', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Uzbekistán', 'fifa_code' => 'UZB', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Vietnam', 'fifa_code' => 'VIE', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],
            ['name' => 'Yemen', 'fifa_code' => 'YEM', 'type' => 'country', 'region' => 'Asia', 'confederation' => 'AFC'],

            // CAF (54 países)
            ['name' => 'Argelia', 'fifa_code' => 'ALG', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Angola', 'fifa_code' => 'ANG', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Benín', 'fifa_code' => 'BEN', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Botsuana', 'fifa_code' => 'BOT', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Burkina Faso', 'fifa_code' => 'BFA', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Burundi', 'fifa_code' => 'BDI', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Cabo Verde', 'fifa_code' => 'CPV', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Camerún', 'fifa_code' => 'CMR', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Chad', 'fifa_code' => 'CHA', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Comoras', 'fifa_code' => 'COM', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Congo', 'fifa_code' => 'CGO', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Congo Democrático', 'fifa_code' => 'COD', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Costa de Marfil', 'fifa_code' => 'CIV', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Djibuti', 'fifa_code' => 'DJI', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Egipto', 'fifa_code' => 'EGY', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Eritrea', 'fifa_code' => 'ERI', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Esuatini', 'fifa_code' => 'SWZ', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Etiopía', 'fifa_code' => 'ETH', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Gabón', 'fifa_code' => 'GAB', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Gambia', 'fifa_code' => 'GAM', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Ghana', 'fifa_code' => 'GHA', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Guinea', 'fifa_code' => 'GUI', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Guinea Ecuatorial', 'fifa_code' => 'EQG', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Guinea-Bisáu', 'fifa_code' => 'GNB', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Kenia', 'fifa_code' => 'KEN', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Lesoto', 'fifa_code' => 'LES', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Liberia', 'fifa_code' => 'LBR', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Libia', 'fifa_code' => 'LBY', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Madagascar', 'fifa_code' => 'MAD', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Malaui', 'fifa_code' => 'MWI', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Mali', 'fifa_code' => 'MLI', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Marruecos', 'fifa_code' => 'MAR', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Mauricio', 'fifa_code' => 'MUS', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Mauritania', 'fifa_code' => 'MTN', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Mozambique', 'fifa_code' => 'MOZ', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Namibia', 'fifa_code' => 'NAM', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Níger', 'fifa_code' => 'NIG', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Nigeria', 'fifa_code' => 'NGR', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'República Centroafricana', 'fifa_code' => 'CTA', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Ruanda', 'fifa_code' => 'RWA', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Sahara Occidental', 'fifa_code' => 'SAH', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'San Tomé y Príncipe', 'fifa_code' => 'STP', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Senegal', 'fifa_code' => 'SEN', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Seychelles', 'fifa_code' => 'SEY', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Sierra Leona', 'fifa_code' => 'SLE', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Somalia', 'fifa_code' => 'SOM', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Sudáfrica', 'fifa_code' => 'RSA', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Sudán', 'fifa_code' => 'SDN', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Sudán del Sur', 'fifa_code' => 'SSD', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Tanzania', 'fifa_code' => 'TAN', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Togo', 'fifa_code' => 'TOG', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Túnez', 'fifa_code' => 'TUN', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Uganda', 'fifa_code' => 'UGA', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Zambia', 'fifa_code' => 'ZAM', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],
            ['name' => 'Zimbabue', 'fifa_code' => 'ZIM', 'type' => 'country', 'region' => 'Africa', 'confederation' => 'CAF'],

            // OFC (15 países)
            ['name' => 'Fiji', 'fifa_code' => 'FIJ', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Guam', 'fifa_code' => 'GUM', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Islas Salomón', 'fifa_code' => 'SOL', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Kiribati', 'fifa_code' => 'KIR', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Micronesia', 'fifa_code' => 'FSM', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Nauru', 'fifa_code' => 'NRU', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Nueva Zelanda', 'fifa_code' => 'NZL', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Palaos', 'fifa_code' => 'PLW', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Papúa Nueva Guinea', 'fifa_code' => 'PNG', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Samoa', 'fifa_code' => 'SAM', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Samoa Americana', 'fifa_code' => 'ASA', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Tahití', 'fifa_code' => 'TAH', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Tonga', 'fifa_code' => 'TGA', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Tuvalu', 'fifa_code' => 'TUV', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
            ['name' => 'Vanuatu', 'fifa_code' => 'VAN', 'type' => 'country', 'region' => 'Oceania', 'confederation' => 'OFC'],
        ];

        // Usar firstOrCreate para evitar duplicados
        foreach ($countries as $country) {
            // Agregar external_id generado para evitar constraint
            $country['external_id'] = 'intl_' . strtolower($country['fifa_code']) . '_' . time();
            
            Team::firstOrCreate(
                ['fifa_code' => $country['fifa_code']], // Buscar por código único
                $country // Crear con estos datos si no existe
            );
        }
        
        $this->command->info('✅ ' . count($countries) . ' países FIFA agregados exitosamente');
    }
}
