<?php

namespace App\Services;

use App\Models\User;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

class AnomalyDetectionService
{
    /**
     * Detector de actividad sospechosa en login
     */
    public static function detectSuspiciousActivity($ip, $username, $userAgent)
    {
        $alerts = [];

        // Alerta 1: Múltiples usuarios creados rápidamente desde misma IP
        $totalKey = 'login_total_' . $ip;
        $totalAttempts = Cache::get($totalKey, 0);
        if ($totalAttempts >= 10) {
            $alerts[] = [
                'type' => 'SPAM_REGISTRATION',
                'severity' => 'HIGH',
                'message' => "Se detectaron $totalAttempts intentos de creación de usuarios desde IP $ip en la última hora",
                'ip' => $ip,
                'detected_at' => now(),
            ];
        }

        // Alerta 2: Mismo usuario creado múltiples veces desde misma IP
        $usernameKey = 'login_username_' . $username . '_' . $ip;
        $usernameAttempts = Cache::get($usernameKey, 0);
        if ($usernameAttempts >= 2) {
            $alerts[] = [
                'type' => 'DUPLICATE_USERNAME',
                'severity' => 'MEDIUM',
                'message' => "Usuario '$username' fue creado $usernameAttempts veces desde IP $ip en 5 minutos",
                'username' => $username,
                'ip' => $ip,
                'detected_at' => now(),
            ];
        }

        // Alerta 3: IP con comportamiento de enumeration
        $enumKey = 'enum_' . $ip;
        $enumAttempts = Cache::get($enumKey, 0);
        if ($enumAttempts >= 50) {
            $alerts[] = [
                'type' => 'ENUMERATION_ATTACK',
                'severity' => 'CRITICAL',
                'message' => "La IP $ip intenta enumerar usuarios (50+ intentos en 1 hora)",
                'ip' => $ip,
                'detected_at' => now(),
            ];
        }

        // Alerta 4: Usernames con patrón automático/generado
        if (self::isAutogeneratedUsername($username)) {
            $alerts[] = [
                'type' => 'AUTOGENERATED_USERNAME',
                'severity' => 'MEDIUM',
                'message' => "Username con patrón automático detectado: '$username' desde IP $ip",
                'username' => $username,
                'ip' => $ip,
                'detected_at' => now(),
            ];
        }

        if (!empty($alerts)) {
            self::logAndNotifyAlerts($alerts, $ip, $username, $userAgent);
        }

        return $alerts;
    }

    /**
     * Detecta si un username parece ser generado automáticamente
     */
    private static function isAutogeneratedUsername($username)
    {
        // Patrones sospechosos:
        // - username_ABC123 (letra + números)
        // - username_123 (números al final)
        // - username_5436 (números largos)

        if (preg_match('/_[A-Z0-9]{4,}$/', $username)) {
            return true;
        }

        if (preg_match('/_\d{2,}$/', $username)) {
            return true;
        }

        return false;
    }

    /**
     * Log y notifica al admin sobre alertas
     */
    private static function logAndNotifyAlerts($alerts, $ip, $username, $userAgent)
    {
        foreach ($alerts as $alert) {
            // Log detallado
            Log::channel('security')->alert("[{$alert['type']}] {$alert['message']}", [
                'severity' => $alert['severity'],
                'ip' => $ip,
                'username' => $username,
                'user_agent' => $userAgent,
                'timestamp' => now(),
            ]);
        }

        // Notificación crítica si hay alertas de severidad CRITICAL
        $criticalAlerts = array_filter($alerts, fn($a) => $a['severity'] === 'CRITICAL');
        if (!empty($criticalAlerts)) {
            self::notifyAdmins($alerts, $ip, $username, $userAgent);
        }
    }

    /**
     * Notifica a los admins mediante email y logs
     */
    private static function notifyAdmins($alerts, $ip, $username, $userAgent)
    {
        try {
            $admins = User::where('is_admin', true)->pluck('email')->toArray();

            if (empty($admins)) {
                Log::warning('No admin users found to notify about security alerts');
                return;
            }

            $alertSummary = implode(
                "\n",
                array_map(fn($a) => "- [{$a['severity']}] {$a['message']}", $alerts)
            );

            $emailContent = "SECURITY ALERT - Suspicious Login Activity\n\n"
                . "Summary:\n$alertSummary\n\n"
                . "Details:\n"
                . "IP: $ip\n"
                . "Username Attempted: $username\n"
                . "User Agent: $userAgent\n"
                . "Timestamp: " . now()->toDateTimeString() . "\n\n"
                . "Action Required: Review and block suspicious IPs in your security settings.";

            // Si tienes un Mail::send configurado, descomenta esto:
            // Mail::raw($emailContent, function ($message) use ($admins) {
            //     $message->to($admins)
            //             ->subject('[SECURITY] Suspicious Login Activity Detected');
            // });

            // Por ahora, solo registramos en logs
            Log::channel('security')->critical('Security alerts sent', [
                'admins_notified' => count($admins),
                'alerts_count' => count($alerts),
            ]);
        } catch (\Exception $e) {
            Log::error('Failed to notify admins about security alerts', [
                'exception' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Verifica si una IP debe ser bloqueada temporalmente
     */
    public static function shouldBlockIp($ip)
    {
        $blockKey = 'blocked_ip_' . $ip;
        return Cache::has($blockKey);
    }

    /**
     * Bloquea una IP temporalmente (24 horas)
     */
    public static function blockIp($ip, $reason = 'Suspicious activity')
    {
        $blockKey = 'blocked_ip_' . $ip;
        Cache::put($blockKey, $reason, 86400); // 24 horas

        Log::warning("IP blocked", [
            'ip' => $ip,
            'reason' => $reason,
            'blocked_until' => now()->addHours(24),
        ]);
    }
}
