#!/bin/bash

# Demo: Force Verify Questions Command

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  DEMO: app:force-verify-questions Command                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📌 Ejemplo 1: Ver ayuda del comando"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ php artisan app:force-verify-questions --help"
echo ""

echo "📌 Ejemplo 2: Verificar preguntas pendientes (dry-run)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ php artisan app:force-verify-questions --dry-run --days=30"
echo ""
echo "Resultado:"
echo "  📖 USAGE:"
echo "    php artisan app:force-verify-questions [OPTIONS]"
echo ""
echo "  📋 OPTIONS:"
echo "    --days=N       Número de días hacia atrás (default: 30)"
echo "    --limit=N      Máximo de matches a verificar (default: 100)"
echo "    --match-id=ID  ID específico del match (omite otros filtros)"
echo "    --re-verify    Re-verificar preguntas ya verificadas"
echo "    --dry-run      Solo previsualizar sin ejecutar"
echo ""
echo "  ❌ No matches found con criterios especificados"
echo "     (Esto es correcto - todas las preguntas ya fueron verificadas)"
echo ""

echo "📌 Ejemplo 3: Re-verificar preguntas (dry-run)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ php artisan app:force-verify-questions --re-verify --dry-run --days=30"
echo ""
echo "Resultado:"
echo "  🔍 FORCE VERIFY QUESTIONS"
echo "  ═════════════════════════════════════════════════════════════════"
echo "  Days back: 30"
echo "  Limit: 100"
echo "  Match ID: ANY"
echo "  Re-verify: YES (Asignará puntos nuevamente)"
echo "  Dry Run: YES"
echo "  ═════════════════════════════════════════════════════════════════"
echo ""
echo "  Buscando matches desde: 2026-01-03 18:36"
echo ""
echo "  ✅ Encontrados 13 matches para RE-VERIFICAR:"
echo ""
echo "    Match #290"
echo "      • Deportivo La Coruna vs Atletico Madrid (3-2)"
echo "      • Fecha: 2026-01-31 20:00"
echo "      • Status: Finished"
echo "      • Preguntas: 6 para re-verificar"
echo ""
echo "    Match #291"
echo "      • Real Sociedad vs Osasuna (2-1)"
echo "      • Fecha: 2026-01-30 19:00"
echo "      • Status: Finished"
echo "      • Preguntas: 3 para re-verificar"
echo ""
echo "    ... y 11 matches más"
echo ""
echo "  ⚠️  DRY RUN MODE: No se ejecutará la verificación"
echo ""
echo "  ℹ️  Para ejecutar realmente, corre sin --dry-run"
echo "  php artisan app:force-verify-questions --re-verify --days=30"
echo ""

echo "📌 Ejemplo 4: Ejecutar re-verificación REAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ php artisan app:force-verify-questions --re-verify --days=30"
echo ""
echo "Resultado:"
echo "  ... (mismo output que arriba pero sin \"DRY RUN MODE\")"
echo ""
echo "  🔄 Reseteando result_verified_at para re-verificación..."
echo ""
echo "  🚀 DISPATCHING VERIFICATION BATCH"
echo "  Batch ID: 8a4e9c2f-3e1d-4b9a-8f5c-1a2b3c4d5e6f"
echo "  Matches: 13"
echo ""
echo "  ✅ Verification batch dispatched successfully"
echo "  📊 Queue will process: BatchGetScoresJob → BatchExtractEventsJob → VerifyAllQuestionsJob"
echo ""
echo "  ✨ Verificación en proceso. Revisa los logs con:"
echo "     tail -f storage/logs/laravel.log | grep 8a4e9c2f"
echo ""

echo "📌 Ejemplo 5: Re-verificar un match específico"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "$ php artisan app:force-verify-questions --match-id=445 --re-verify --dry-run"
echo ""
echo "Resultado:"
echo "  🔍 FORCE VERIFY QUESTIONS"
echo "  ═════════════════════════════════════════════════════════════════"
echo "  Days back: 30"
echo "  Limit: 100"
echo "  Match ID: 445"
echo "  Re-verify: YES (Asignará puntos nuevamente)"
echo "  Dry Run: YES"
echo "  ═════════════════════════════════════════════════════════════════"
echo ""
echo "  Buscando match específico: #445"
echo ""
echo "  ✅ Encontrados 1 matches para RE-VERIFICAR:"
echo ""
echo "    Match #445"
echo "      • Real Madrid vs Monaco (6-1)"
echo "      • Fecha: 2026-01-31 20:00"
echo "      • Status: Finished"
echo "      • Preguntas: 5 para re-verificar"
echo ""
echo "  ⚠️  DRY RUN MODE: No se ejecutará la verificación"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  NOTAS IMPORTANTES                                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "⚠️  Re-verify limpia puntos previamente asignados"
echo "    Los usuarios perderán/recibirán puntos basado en la nueva verificación"
echo ""
echo "⚡ El queue worker debe estar corriendo:"
echo "   php artisan queue:work"
echo ""
echo "📊 Monitorea el progreso:"
echo "   tail -f storage/logs/laravel.log | grep VerifyAllQuestionsJob"
echo ""
echo "📖 Para más detalles, ver: FORCE_VERIFY_GUIDE.md"
echo ""
