-- Consultas INSERT para las preguntas del máster
-- Cada pregunta se inserta con valores similares al ejemplo proporcionado

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién llegará más tarde al día de graduación?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién comerá más en la cena de graduación?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién bebió más litros de alcohol durante el máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién hizo la presentación más recordada del máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién fue el más sentimental durante el máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién fue el más insensible del máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién tiene el mejor outfit / style del máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, 'Si hay que negociar que nos den "regalos" o "regatear" en la cena, ¿a quién mandaríamos?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién fue el más participativo de clase?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién confundiría la fecha/lugar de graduación si no le advierten antes?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién es el más organizado en sus apuntes / escritorio?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién es el/la más amoroso/a del máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién es el/la más gracioso/a del máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién es el que más comparte stickers en el chat del máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién es el más rápido en responder el chat del máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién tiene la mejor voz del máster?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);

INSERT INTO `questions` (`id`, `title`, `description`, `type`, `category`, `points`, `group_id`, `match_id`, `available_until`, `is_featured`, `created_at`, `updated_at`, `football_match_id`, `result_verified_at`, `template_question_id`, `competition_id`, `deleted_at`) VALUES (NULL, '¿Quién ha asistido a más eventos extracurriculares?', NULL, 'predictive', NULL, '300', '75', NULL, NOW(), '1', '2025-06-23 17:31:16', '2025-06-23 17:31:16', NULL, NULL, '20', '4', NULL);
