-- SINCRONIZACIÓN CORRECTA DE EQUIPOS - 80 EQUIPOS

UPDATE teams SET api_name = 'AC Milan' WHERE name = 'AC Milan';
UPDATE teams SET api_name = 'AC Pisa 1909' WHERE name = 'AC Pisa 1909';
UPDATE teams SET api_name = 'ACF Fiorentina' WHERE name = 'ACF Fiorentina';
UPDATE teams SET api_name = 'AFC Ajax' WHERE name = 'AFC Ajax';
UPDATE teams SET api_name = 'AFC Bournemouth' WHERE name = 'AFC Bournemouth';
UPDATE teams SET api_name = 'Arsenal FC' WHERE name = 'Arsenal';
UPDATE teams SET api_name = 'AS Monaco FC' WHERE name = 'AS Monaco FC';
UPDATE teams SET api_name = 'AS Roma' WHERE name = 'AS Roma';
UPDATE teams SET api_name = 'Aston Villa FC' WHERE name = 'Aston Villa';
UPDATE teams SET api_name = 'Atalanta BC' WHERE name = 'Atalanta';
UPDATE teams SET api_name = 'Athletic Club' WHERE name = 'Athletic';
UPDATE teams SET api_name = 'Bayer 04 Leverkusen' WHERE name = 'Bayer 04 Leverkusen';
UPDATE teams SET api_name = 'Bologna FC 1909' WHERE name = 'Bologna FC 1909';
UPDATE teams SET api_name = 'Borussia Dortmund' WHERE name = 'Borussia Dortmund';
UPDATE teams SET api_name = 'Brentford FC' WHERE name = 'Brentford';
UPDATE teams SET api_name = 'Brighton & Hove Albion FC' WHERE name = 'Brighton & Hove Albion FC';
UPDATE teams SET api_name = 'Burnley FC' WHERE name = 'Burnley FC';
UPDATE teams SET api_name = 'CA Osasuna' WHERE name = 'CA Osasuna';
UPDATE teams SET api_name = 'Cagliari Calcio' WHERE name = 'Cagliari Calcio';
UPDATE teams SET api_name = 'Chelsea FC' WHERE name = 'Chelsea';
UPDATE teams SET api_name = 'Club Atlético de Madrid' WHERE name = 'Club Atlético de Madrid';
UPDATE teams SET api_name = 'Club Brugge KV' WHERE name = 'Club Brugge KV';
UPDATE teams SET api_name = 'Como 1907' WHERE name = 'Como 1907';
UPDATE teams SET api_name = 'Crystal Palace FC' WHERE name = 'Crystal Palace';
UPDATE teams SET api_name = 'Deportivo Alavés' WHERE name = 'Deportivo Alavés';
UPDATE teams SET api_name = 'Eintracht Frankfurt' WHERE name = 'Eintracht Frankfurt';
UPDATE teams SET api_name = 'Elche CF' WHERE name = 'Elche';
UPDATE teams SET api_name = 'Everton FC' WHERE name = 'Everton';
UPDATE teams SET api_name = 'FC Barcelona' WHERE name = 'FC Barcelona';
UPDATE teams SET api_name = 'FC Bayern München' WHERE name = 'FC Bayern München';
UPDATE teams SET api_name = 'FC Internazionale Milano' WHERE name = 'FC Internazionale Milano';
UPDATE teams SET api_name = 'FC København' WHERE name = 'FC København';
UPDATE teams SET api_name = 'FK Bodø/Glimt' WHERE name = 'FK Bodø/Glimt';
UPDATE teams SET api_name = 'FK Kairat' WHERE name = 'FK Kairat';
UPDATE teams SET api_name = 'Fulham FC' WHERE name = 'Fulham';
UPDATE teams SET api_name = 'Galatasaray SK' WHERE name = 'Galatasaray SK';
UPDATE teams SET api_name = 'Genoa CFC' WHERE name = 'Genoa CFC';
UPDATE teams SET api_name = 'Getafe CF' WHERE name = 'Getafe CF';
UPDATE teams SET api_name = 'Girona FC' WHERE name = 'Girona FC';
UPDATE teams SET api_name = 'Hellas Verona FC' WHERE name = 'Hellas Verona FC';
UPDATE teams SET api_name = 'Juventus FC' WHERE name = 'Juventus';
UPDATE teams SET api_name = 'Leeds United FC' WHERE name = 'Leeds United FC';
UPDATE teams SET api_name = 'Levante UD' WHERE name = 'Levante UD';
UPDATE teams SET api_name = 'Liverpool FC' WHERE name = 'Liverpool';
UPDATE teams SET api_name = 'Manchester City FC' WHERE name = 'Manchester City';
UPDATE teams SET api_name = 'Manchester United FC' WHERE name = 'Manchester United FC';
UPDATE teams SET api_name = 'Newcastle United FC' WHERE name = 'Newcastle United FC';
UPDATE teams SET api_name = 'Nottingham Forest FC' WHERE name = 'Nottingham Forest FC';
UPDATE teams SET api_name = 'Olympique de Marseille' WHERE name = 'Olympique de Marseille';
UPDATE teams SET api_name = 'PAE Olympiakos SFP' WHERE name = 'PAE Olympiakos SFP';
UPDATE teams SET api_name = 'Paphos FC' WHERE name = 'Paphos FC';
UPDATE teams SET api_name = 'Paris Saint-Germain FC' WHERE name = 'Paris Saint-Germain FC';
UPDATE teams SET api_name = 'Parma Calcio 1913' WHERE name = 'Parma Calcio 1913';
UPDATE teams SET api_name = 'PSV' WHERE name = 'PSV';
UPDATE teams SET api_name = 'Qarabağ Ağdam FK' WHERE name = 'Qarabağ Ağdam FK';
UPDATE teams SET api_name = 'Rayo Vallecano de Madrid' WHERE name = 'Rayo Vallecano de Madrid';
UPDATE teams SET api_name = 'RC Celta de Vigo' WHERE name = 'RC Celta de Vigo';
UPDATE teams SET api_name = 'RCD Espanyol de Barcelona' WHERE name = 'RCD Espanyol de Barcelona';
UPDATE teams SET api_name = 'RCD Mallorca' WHERE name = 'RCD Mallorca';
UPDATE teams SET api_name = 'Real Betis Balompié' WHERE name = 'Real Betis Balompié';
UPDATE teams SET api_name = 'Real Madrid CF' WHERE name = 'Real Madrid';
UPDATE teams SET api_name = 'Real Oviedo' WHERE name = 'Real Oviedo';
UPDATE teams SET api_name = 'Real Sociedad de Fútbol' WHERE name = 'Real Sociedad de Fútbol';
UPDATE teams SET api_name = 'Royale Union Saint-Gilloise' WHERE name = 'Royale Union Saint-Gilloise';
UPDATE teams SET api_name = 'Sevilla FC' WHERE name = 'Sevilla FC';
UPDATE teams SET api_name = 'SK Slavia Praha' WHERE name = 'SK Slavia Praha';
UPDATE teams SET api_name = 'Sport Lisboa e Benfica' WHERE name = 'Sport Lisboa e Benfica';
UPDATE teams SET api_name = 'Sporting Clube de Portugal' WHERE name = 'Sporting Clube de Portugal';
UPDATE teams SET api_name = 'SS Lazio' WHERE name = 'SS Lazio';
UPDATE teams SET api_name = 'SSC Napoli' WHERE name = 'SSC Napoli';
UPDATE teams SET api_name = 'Sunderland AFC' WHERE name = 'Sunderland AFC';
UPDATE teams SET api_name = 'Torino FC' WHERE name = 'Torino FC';
UPDATE teams SET api_name = 'Tottenham Hotspur FC' WHERE name = 'Tottenham Hotspur FC';
UPDATE teams SET api_name = 'Udinese Calcio' WHERE name = 'Udinese Calcio';
UPDATE teams SET api_name = 'US Cremonese' WHERE name = 'US Cremonese';
UPDATE teams SET api_name = 'US Lecce' WHERE name = 'US Lecce';
UPDATE teams SET api_name = 'US Sassuolo Calcio' WHERE name = 'US Sassuolo Calcio';
UPDATE teams SET api_name = 'Valencia CF' WHERE name = 'Valencia CF';
UPDATE teams SET api_name = 'Villarreal CF' WHERE name = 'Villarreal CF';
UPDATE teams SET api_name = 'West Ham United FC' WHERE name = 'West Ham United FC';
UPDATE teams SET api_name = 'Wolverhampton Wanderers FC' WHERE name = 'Wolverhampton Wanderers FC';
